### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Freivincampbell** [AlexRojasB/AgeInfo#8]
**spacing**
The cars' spacing is distinct in all sides

**To Reproduce**
1. Open the app
2. Go to Home Screen 
3. See the spaces 

**Screenshots**
![image](https://user-images.githubusercontent.com/7534967/122461379-80419300-cf70-11eb-93aa-1e8ca4b977fd.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max 
 - OS: 14.6
 - App 1.0.4

**Comment by AlexRojasB** [comment]
The card width was increased to use all the space and avoid cut the some words
