### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Freivincampbell** [AlexRojasB/AgeInfo#9]
**Describe the bug**
Age number is cutting of by card 
**To Reproduce**
1. Go to Home Screen 
2. Open age card
3. See the age 

**Expected behavior**
The possibility to have the age as title of the card / part of my view 

**Screenshots**
![image](https://user-images.githubusercontent.com/7534967/122461882-255c6b80-cf71-11eb-859c-e3cdd2530e90.jpeg)
![image](https://user-images.githubusercontent.com/7534967/122461904-2b524c80-cf71-11eb-9169-a603a3e7692c.png)
**Smartphone (please complete the following information):**
 - Device: iPhone XS Max 
 - OS: 14.6
 - App Version 1.0.4

**Comment by AlexRojasB** [comment]
The animation was removed and let just the date transition
